
{
    'name': "Prodal",
    'summary': """
        Mejoras generales de prodal""",
    'author': "Atrivia",
    'website': "https://www.atrivia.do/",
    'category': 'Uncategorized',
    'version': '13.0.1.0.1',
    'depends': [
        'fleet',
        'hr',
        'sale_management',
        'stock_picking_batch',
        'prodal_account',
        'crm',
        'product_template_offer',
        'stock_picking_back2draft',
        'atrivia_invoice_elapsed_days'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/dp_data.xml',
        'data/sequence_data.xml',
        'data/paper_format.xml',
        'views/product_pricelist.xml',
        'data/records.xml',
        'views/menu.xml',
        'views/menu_view.xml',
        'views/zone_view.xml',
        'views/sale_order_view.xml',
        'wizard/picking_change_operation_view.xml',
        'views/stock_picking.xml',
        'views/product_template.xml',
        'views/fleet_vehicle.xml',
        'views/stock_quant.xml',
        'views/product_category_view.xml',
        'reports/report_templates.xml',
        'reports/paper_data.xml',
        'views/stock_reports.xml',
        'views/hr_employee.xml',
        'views/res_partner.xml',
        'views/uom_uom.xml',
        'views/account_move.xml',
        'views/account_payment_term.xml',
        'views/report_journal.xml',
        'views/account_report.xml',
        'views/res_config.xml',
        'views/stock_picking_message.xml',
        'reports/report_load_truck.xml',
        'reports/report_prodal_packing_list.xml',
        'reports/report_prodal_transfer.xml',
        'reports/report_prodal_internal_transfer.xml',
        'reports/report_prodal_load_squaring.xml',
        'reports/report_invoice_list.xml',
        'reports/report_mrp_stock_move_lines_view.xml',
        'views/report_menu.xml',
        'views/res_users.xml',
        'wizard/inventory_report_template.xml',
        'wizard/inventory_report_view.xml',
        'wizard/prodal_invoice_list_wizard_view.xml',
        'wizard/account_report_common_view.xml',
        'reports/inventory_report_quintals.xml',
        'wizard/inventory_report_quintals_wizard.xml',
        'data/base_automation.xml',
    ],
}
