from . import referrer
from . import res_partner
from . import product
from . import insurance_close_reason
from . import account_move
from . import account_payment
from . import res_config_settings
from . import check_config_report
from . import account_pay